/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who changed what in this workspace, newest first */
        get: operations["AuditController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign in
         * @description Sends a verification email. The refresh token is set as an httpOnly cookie.
         */
        post: operations["AuthController_signup_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a new access token
         * @description Rotates the refresh cookie. Requires the `x-tasknest-csrf` header. Presenting an already-used refresh token revokes the whole session.
         */
        post: operations["AuthController_refresh_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out of this browser */
        post: operations["AuthController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["AuthController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browsers and devices currently signed in to this account */
        get: operations["AuthController_listSessions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign out a specific browser or device */
        delete: operations["AuthController_revokeSession_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an email address with the emailed token */
        post: operations["AuthController_verifyEmail_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send the verification email again */
        post: operations["AuthController_resendVerification_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a password reset link
         * @description Always returns 202, whether or not the email has an account.
         */
        post: operations["AuthController_forgotPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password with the emailed token; signs out everywhere */
        post: operations["AuthController_resetPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password; signs out every other session */
        post: operations["AuthController_changePassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roles in this workspace and what each one allows */
        get: operations["RolesController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every permission a role can grant */
        get: operations["RolesController_catalog_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. Succeeds while the process can serve HTTP. */
        get: operations["HealthController_live_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe. Returns 503 when a dependency the API needs is unreachable. */
        get: operations["HealthController_ready_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspaces you belong to, with your role in each */
        get: operations["OrganizationsController_listMine_v1"];
        put?: never;
        /** Create a workspace; you become its owner */
        post: operations["OrganizationsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The workspace selected by the organization header */
        get: operations["OrganizationsController_current_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename the workspace or change its business type or time zone */
        patch: operations["OrganizationsController_update_v1"];
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everyone in this workspace, with role and teams */
        get: operations["MembersController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove someone from the workspace */
        delete: operations["MembersController_remove_v1"];
        options?: never;
        head?: never;
        /**
         * Change a member’s role, or disable and re-enable their access
         * @description You cannot change yourself. Only owners can grant the owner role or change another owner.
         */
        patch: operations["MembersController_update_v1"];
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Teams in this workspace and who is on each */
        get: operations["TeamsController_list_v1"];
        put?: never;
        /** Create a team */
        post: operations["TeamsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a team; its members stay in the workspace */
        delete: operations["TeamsController_remove_v1"];
        options?: never;
        head?: never;
        /** Rename a team or change its description */
        patch: operations["TeamsController_update_v1"];
        trace?: never;
    };
    "/api/v1/teams/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set exactly who is on a team */
        put: operations["TeamsController_setMembers_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invitations that have not been accepted, revoked or expired */
        get: operations["InvitationsController_list_v1"];
        put?: never;
        /** Invite someone by email; replaces any pending invitation for them */
        post: operations["InvitationsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel a pending invitation */
        delete: operations["InvitationsController_revoke_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who invited you, to which workspace, as what role */
        get: operations["InvitationsController_preview_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join the workspace
         * @description You must be signed in with the email address the invitation was sent to.
         */
        post: operations["InvitationsController_accept_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contacts, newest first, with search and filters */
        get: operations["ContactsController_list_v1"];
        put?: never;
        /** Add a contact by hand */
        post: operations["ContactsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One contact with tags and channel identities */
        get: operations["ContactsController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a contact with its notes and history */
        delete: operations["ContactsController_remove_v1"];
        options?: never;
        head?: never;
        /** Edit contact details; send null or "" to clear a field */
        patch: operations["ContactsController_update_v1"];
        trace?: never;
    };
    "/api/v1/contacts/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set exactly which tags a contact has */
        put: operations["ContactsController_setTags_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The contact's timeline, newest first */
        get: operations["ContactsController_listActivity_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Internal notes about the contact, newest first */
        get: operations["ContactsController_listNotes_v1"];
        put?: never;
        /** Add an internal note. Customers never see notes. */
        post: operations["ContactsController_addNote_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a note you wrote (or any note with contact.delete) */
        delete: operations["ContactsController_removeNote_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tags in this workspace and how many contacts use each */
        get: operations["TagsController_list_v1"];
        put?: never;
        /** Create a tag */
        post: operations["TagsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a tag and remove it from every contact */
        delete: operations["TagsController_remove_v1"];
        options?: never;
        head?: never;
        /** Rename or recolor a tag */
        patch: operations["TagsController_update_v1"];
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The catalogue, newest first */
        get: operations["ProductsController_list_v1"];
        put?: never;
        /** Add a product */
        post: operations["ProductsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a product, or archive it so it cannot be ordered */
        patch: operations["ProductsController_update_v1"];
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders, newest first. Search by order number or customer. */
        get: operations["OrdersController_list_v1"];
        put?: never;
        /**
         * Record an order
         * @description Prices come from the catalogue. Linking a contact makes them a customer.
         */
        post: operations["OrdersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How much a contact has ordered and spent */
        get: operations["OrdersController_summary_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrdersController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update status, carrier, tracking number or delivery estimate */
        patch: operations["OrdersController_update_v1"];
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conversations, most recent activity first, with filters */
        get: operations["ConversationsController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many open conversations are in each inbox view */
        get: operations["ConversationsController_counts_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConversationsController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change status or priority; status changes are noted in the thread */
        patch: operations["ConversationsController_update_v1"];
        trace?: never;
    };
    "/api/v1/conversations/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign to a member and/or team, or unassign with null */
        post: operations["ConversationsController_assign_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set exactly which tags a conversation has */
        put: operations["ConversationsController_setTags_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark everything in the conversation as read for you */
        post: operations["ConversationsController_markRead_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Messages and notes, a page at a time going back in time */
        get: operations["ConversationsController_listMessages_v1"];
        put?: never;
        /**
         * Reply to the customer, or add an internal note
         * @description A reply takes the conversation over from the AI, reopens it if resolved, and assigns it to you if nobody had it.
         */
        post: operations["ConversationsController_send_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditLogDto: {
            id: string;
            /** @enum {string} */
            actorType: "USER" | "SYSTEM" | "AI" | "API_KEY";
            actorId: string | null;
            actorLabel: string | null;
            action: string;
            entityType: string;
            entityId: string | null;
            ip: string | null;
            metadata: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt: string;
        };
        AuditLogPageDto: {
            data: components["schemas"]["AuditLogDto"][];
            nextCursor: string | null;
        };
        SignupDto: {
            /** @example Maya Chen */
            name: string;
            /**
             * Format: email
             * @example maya@northstarcoffee.co
             */
            email: string;
            /** @description At least 10 characters. Passphrases are welcome. */
            password: string;
        };
        UserDto: {
            id: string;
            email: string;
            name: string;
            emailVerified: boolean;
            avatarUrl: string | null;
        };
        AuthResponseDto: {
            /** @description Short-lived bearer token. Keep it in memory, not in storage. */
            accessToken: string;
            /** @description Seconds until `accessToken` expires. */
            expiresIn: number;
            user: components["schemas"]["UserDto"];
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        SessionDto: {
            id: string;
            ip: string | null;
            userAgent: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string;
            /** @description True for the session that made this request. */
            current: boolean;
        };
        TokenDto: {
            /** @description The token from the emailed link. */
            token: string;
        };
        EmailDto: {
            /** Format: email */
            email: string;
        };
        ResetPasswordDto: {
            /** @description The token from the emailed link. */
            token: string;
            password: string;
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        RoleDto: {
            id: string;
            key: string;
            name: string;
            description: string | null;
            isSystem: boolean;
            permissions: string[];
            memberCount: number;
        };
        PermissionDto: {
            /** @example conversation.reply */
            key: string;
            description: string;
        };
        CreateOrganizationDto: {
            /** @example Northstar Coffee */
            name: string;
            /** @enum {string} */
            businessType?: "ecommerce" | "d2c" | "saas" | "services" | "agency" | "education" | "clinic" | "other";
            /**
             * @description IANA time zone used for business hours and reports.
             * @example America/Chicago
             */
            timezone?: string;
        };
        MembershipRoleDto: {
            key: string;
            name: string;
        };
        MyOrganizationDto: {
            /** @description Your membership in this workspace; matches `id` in the members list. */
            memberId: string;
            /** @description Your role in this workspace. */
            role: components["schemas"]["MembershipRoleDto"];
            /** @description Permission keys your role grants, for showing or hiding UI. */
            permissions: string[];
            id: string;
            name: string;
            slug: string;
            businessType: string | null;
            timezone: string;
            /** Format: date-time */
            createdAt: string;
        };
        OrganizationDto: {
            id: string;
            name: string;
            slug: string;
            businessType: string | null;
            timezone: string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateOrganizationDto: {
            name?: string;
            /** @enum {string} */
            businessType?: "ecommerce" | "d2c" | "saas" | "services" | "agency" | "education" | "clinic" | "other";
            timezone?: string;
        };
        MemberUserDto: {
            id: string;
            name: string;
            email: string;
            avatarUrl: string | null;
        };
        RoleRefDto: {
            id: string;
            key: string;
            name: string;
        };
        TeamRefDto: {
            id: string;
            name: string;
        };
        MemberDto: {
            id: string;
            /** @enum {string} */
            status: "ACTIVE" | "DISABLED";
            displayName: string | null;
            /** Format: date-time */
            joinedAt: string;
            user: components["schemas"]["MemberUserDto"];
            role: components["schemas"]["RoleRefDto"];
            teams: components["schemas"]["TeamRefDto"][];
        };
        UpdateMemberDto: {
            /** Format: uuid */
            roleId?: string;
            /**
             * @description Disabled members keep their history but cannot open the workspace.
             * @enum {string}
             */
            status?: "ACTIVE" | "DISABLED";
        };
        TeamMemberRefDto: {
            id: string;
            name: string;
        };
        TeamDto: {
            id: string;
            name: string;
            description: string | null;
            members: components["schemas"]["TeamMemberRefDto"][];
            /** Format: date-time */
            createdAt: string;
        };
        CreateTeamDto: {
            /** @example Customer Care */
            name: string;
            /** @example Orders, shipping, subscriptions and returns. */
            description?: string;
        };
        UpdateTeamDto: {
            name?: string;
            description?: string;
        };
        SetTeamMembersDto: {
            /** @description The full list of member ids; anyone not listed is removed from the team. */
            memberIds: string[];
        };
        CreateInvitationDto: {
            /**
             * Format: email
             * @example tom@northstarcoffee.co
             */
            email: string;
            /** Format: uuid */
            roleId: string;
        };
        InvitationDto: {
            id: string;
            email: string;
            role: components["schemas"]["RoleRefDto"];
            invitedBy: string | null;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        InvitationPreviewDto: {
            organizationName: string;
            invitedBy: string | null;
            email: string;
            roleName: string;
            /** Format: date-time */
            expiresAt: string;
        };
        InvitationTokenDto: {
            token: string;
        };
        TagDto: {
            id: string;
            name: string;
            color: string;
        };
        ContactDto: {
            id: string;
            /** @description Name, or email, or phone: whatever identifies the contact best. */
            displayName: string;
            name: string | null;
            email: string | null;
            phone: string | null;
            company: string | null;
            location: string | null;
            /** @enum {string} */
            stage: "VISITOR" | "LEAD" | "CUSTOMER";
            /** Format: date-time */
            lastSeenAt: string | null;
            /** Format: date-time */
            createdAt: string;
            tags: components["schemas"]["TagDto"][];
        };
        ContactPageDto: {
            data: components["schemas"]["ContactDto"][];
            nextCursor: string | null;
        };
        CreateContactDto: {
            tagIds?: string[];
            /** @example Sarah Mitchell */
            name?: string | null;
            /**
             * Format: email
             * @example sarah.mitchell@gmail.com
             */
            email?: string | null;
            /**
             * @description Any format people type; stored as entered.
             * @example +1 512 555 0143
             */
            phone?: string | null;
            company?: string | null;
            /** @example Austin, TX */
            location?: string | null;
            /** @enum {string} */
            stage?: "VISITOR" | "LEAD" | "CUSTOMER";
        };
        ContactIdentityDto: {
            /** @enum {string} */
            channel: "EMAIL" | "PHONE" | "WEBSITE_CHAT" | "TELEGRAM" | "WHATSAPP" | "MESSENGER" | "INSTAGRAM";
            externalId: string;
        };
        ContactDetailDto: {
            id: string;
            /** @description Name, or email, or phone: whatever identifies the contact best. */
            displayName: string;
            name: string | null;
            email: string | null;
            phone: string | null;
            company: string | null;
            location: string | null;
            /** @enum {string} */
            stage: "VISITOR" | "LEAD" | "CUSTOMER";
            /** Format: date-time */
            lastSeenAt: string | null;
            /** Format: date-time */
            createdAt: string;
            tags: components["schemas"]["TagDto"][];
            identities: components["schemas"]["ContactIdentityDto"][];
            noteCount: number;
        };
        UpdateContactDto: {
            /** @example Sarah Mitchell */
            name?: string | null;
            /**
             * Format: email
             * @example sarah.mitchell@gmail.com
             */
            email?: string | null;
            /**
             * @description Any format people type; stored as entered.
             * @example +1 512 555 0143
             */
            phone?: string | null;
            company?: string | null;
            /** @example Austin, TX */
            location?: string | null;
            /** @enum {string} */
            stage?: "VISITOR" | "LEAD" | "CUSTOMER";
        };
        SetContactTagsDto: {
            tagIds: string[];
        };
        ActivityDto: {
            id: string;
            type: string;
            actorLabel: string | null;
            metadata: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt: string;
        };
        ActivityPageDto: {
            data: components["schemas"]["ActivityDto"][];
            nextCursor: string | null;
        };
        NoteDto: {
            id: string;
            body: string;
            author: {
                id: string;
                name: string;
            };
            /** Format: date-time */
            createdAt: string;
        };
        NotePageDto: {
            data: components["schemas"]["NoteDto"][];
            nextCursor: string | null;
        };
        CreateNoteDto: {
            body: string;
        };
        TagWithUsageDto: {
            id: string;
            name: string;
            color: string;
            contactCount: number;
        };
        CreateTagDto: {
            name: string;
            /** @enum {string} */
            color?: "slate" | "blue" | "green" | "amber" | "red" | "violet" | "teal" | "pink";
        };
        UpdateTagDto: {
            name?: string;
            /** @enum {string} */
            color?: "slate" | "blue" | "green" | "amber" | "red" | "violet" | "teal" | "pink";
        };
        ProductDto: {
            id: string;
            name: string;
            sku: string | null;
            description: string | null;
            category: string | null;
            priceCents: number;
            currency: string;
            stockQuantity: number | null;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED";
            /** Format: date-time */
            createdAt: string;
        };
        ProductPageDto: {
            data: components["schemas"]["ProductDto"][];
            nextCursor: string | null;
        };
        CreateProductDto: {
            /** @example Ethiopia Guji, 12 oz */
            name: string;
            /** @example ETH-GUJI-12 */
            sku?: string | null;
            description?: string | null;
            /** @example Coffee */
            category?: string | null;
            /**
             * @description In cents.
             * @example 1900
             */
            priceCents: number;
            /**
             * @description ISO 4217.
             * @example USD
             */
            currency?: string;
            /** @description Leave empty if stock is not tracked. */
            stockQuantity?: number | null;
        };
        UpdateProductDto: {
            name?: string;
            sku?: string | null;
            description?: string | null;
            category?: string | null;
            priceCents?: number;
            stockQuantity?: number | null;
            /** @enum {string} */
            status?: "ACTIVE" | "ARCHIVED";
        };
        OrderContactDto: {
            id: string;
            displayName: string;
            email: string | null;
        };
        OrderSummaryDto: {
            id: string;
            number: number;
            /** @enum {string} */
            status: "PENDING" | "PAID" | "FULFILLED" | "SHIPPED" | "DELIVERED" | "CANCELLED" | "REFUNDED";
            currency: string;
            totalCents: number;
            itemCount: number;
            /** Format: date-time */
            placedAt: string;
            contact: components["schemas"]["OrderContactDto"] | null;
        };
        OrderPageDto: {
            data: components["schemas"]["OrderSummaryDto"][];
            /** @description Pass back as `cursor`; orders are listed newest number first. */
            nextCursor: number | null;
        };
        CustomerOrdersSummaryDto: {
            orderCount: number;
            /** @description Paid, shipped or delivered orders only; refunds and cancellations excluded. */
            totalSpentCents: number;
            currency: string;
            /** Format: date-time */
            lastOrderAt: string | null;
        };
        OrderLineInputDto: {
            /** Format: uuid */
            productId: string;
            quantity: number;
        };
        CreateOrderDto: {
            /** Format: uuid */
            contactId?: string;
            items: components["schemas"]["OrderLineInputDto"][];
            /** @description In cents. */
            shippingCents?: number;
            shippingAddress?: string | null;
            /** @enum {string} */
            status?: "PENDING" | "PAID" | "FULFILLED" | "SHIPPED" | "DELIVERED" | "CANCELLED" | "REFUNDED";
        };
        OrderItemDto: {
            id: string;
            productId: string | null;
            name: string;
            sku: string | null;
            unitPriceCents: number;
            quantity: number;
            totalCents: number;
        };
        OrderDto: {
            id: string;
            number: number;
            /** @enum {string} */
            status: "PENDING" | "PAID" | "FULFILLED" | "SHIPPED" | "DELIVERED" | "CANCELLED" | "REFUNDED";
            currency: string;
            totalCents: number;
            itemCount: number;
            /** Format: date-time */
            placedAt: string;
            contact: components["schemas"]["OrderContactDto"] | null;
            subtotalCents: number;
            shippingCents: number;
            shippingAddress: string | null;
            carrier: string | null;
            trackingNumber: string | null;
            /** @description Calendar date, YYYY-MM-DD. */
            estimatedDelivery: string | null;
            items: components["schemas"]["OrderItemDto"][];
        };
        UpdateOrderDto: {
            /** @enum {string} */
            status?: "PENDING" | "PAID" | "FULFILLED" | "SHIPPED" | "DELIVERED" | "CANCELLED" | "REFUNDED";
            /** @example UPS */
            carrier?: string | null;
            trackingNumber?: string | null;
            /** @example 2026-10-08 */
            estimatedDelivery?: string | null;
        };
        ChannelRefDto: {
            id: string;
            /** @enum {string} */
            type: "EMAIL" | "PHONE" | "WEBSITE_CHAT" | "TELEGRAM" | "WHATSAPP" | "MESSENGER" | "INSTAGRAM";
            name: string;
        };
        ConversationContactDto: {
            id: string;
            displayName: string;
            email: string | null;
            /** @enum {string} */
            stage: "VISITOR" | "LEAD" | "CUSTOMER";
        };
        MemberRefDto: {
            id: string;
            name: string;
        };
        ConversationDto: {
            id: string;
            subject: string | null;
            /** @enum {string} */
            status: "PENDING" | "OPEN" | "RESOLVED" | "CLOSED";
            /** @enum {string} */
            handler: "AI_HANDLING" | "HUMAN_HANDLING" | "AI_ESCALATED";
            /** @enum {string} */
            priority: "LOW" | "NORMAL" | "HIGH" | "URGENT";
            escalationReason: string | null;
            channel: components["schemas"]["ChannelRefDto"];
            contact: components["schemas"]["ConversationContactDto"];
            assignee: components["schemas"]["MemberRefDto"] | null;
            team: components["schemas"]["TeamRefDto"] | null;
            tags: components["schemas"]["TagDto"][];
            /** Format: date-time */
            lastMessageAt: string;
            lastMessagePreview: string | null;
            /** @description Customer messages you have not read yet. */
            unreadCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        ConversationPageDto: {
            data: components["schemas"]["ConversationDto"][];
            nextCursor: string | null;
        };
        InboxCountsDto: {
            /** @description Open or pending, in each view. */
            all: number;
            mine: number;
            unassigned: number;
            team: number;
        };
        UpdateConversationDto: {
            /** @enum {string} */
            status?: "PENDING" | "OPEN" | "RESOLVED" | "CLOSED";
            /** @enum {string} */
            priority?: "LOW" | "NORMAL" | "HIGH" | "URGENT";
        };
        AssignConversationDto: {
            /**
             * Format: uuid
             * @description Member id, or null to unassign.
             */
            assigneeId: string | null;
            /**
             * Format: uuid
             * @description Team id, or null to clear. Omit to leave the team unchanged.
             */
            teamId?: string | null;
        };
        SetConversationTagsDto: {
            tagIds: string[];
        };
        MessageDto: {
            id: string;
            conversationId: string;
            /** @enum {string} */
            sender: "SYSTEM" | "AI" | "CONTACT" | "MEMBER";
            internal: boolean;
            body: string;
            author: components["schemas"]["MemberRefDto"] | null;
            metadata: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt: string;
        };
        MessagePageDto: {
            /** @description Oldest first, ready to render top to bottom. */
            data: components["schemas"]["MessageDto"][];
            /** @description Pass as `before` to load the page above, or null at the start of the conversation. */
            nextBefore: string | null;
        };
        SendMessageDto: {
            body: string;
            /** @description An internal note: visible to the team, never sent to the customer. */
            internal?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuditController_list_v1: {
        parameters: {
            query: {
                limit: number;
                /** @description `nextCursor` from the previous page. */
                cursor?: string;
                action?: string;
                entityType?: string;
                actorId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPageDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `audit.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signup_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description `EMAIL_TAKEN` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description `INVALID_CREDENTIALS` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description `SESSION_EXPIRED` or `SESSION_REVOKED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_listSessions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"][];
                };
            };
        };
    };
    AuthController_revokeSession_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyEmail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resendVerification_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"][];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_catalog_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionDto"][];
                };
            };
        };
    };
    HealthController_live_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_ready_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_listMine_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyOrganizationDto"][];
                };
            };
        };
    };
    OrganizationsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyOrganizationDto"];
                };
            };
        };
    };
    OrganizationsController_current_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: nothing extra */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `settings.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDto"][];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamsController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDto"][];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamsController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamsController_setMembers_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTeamMembersDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationsController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationDto"][];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationsController_revoke_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `team.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationsController_preview_v1: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreviewDto"];
                };
            };
        };
    };
    InvitationsController_accept_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyOrganizationDto"];
                };
            };
        };
    };
    ContactsController_list_v1: {
        parameters: {
            query: {
                /** @description Matches name, email, phone or company. */
                search?: string;
                stage?: "VISITOR" | "LEAD" | "CUSTOMER";
                tagId?: string;
                cursor?: string;
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactPageDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDetailDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.update` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `CONTACT_EMAIL_TAKEN`, with the existing contact id */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactsController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDetailDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactsController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.delete` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContactDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDetailDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.update` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactsController_setTags_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetContactTagsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDetailDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.update` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactsController_listActivity_v1: {
        parameters: {
            query: {
                cursor?: string;
                limit: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPageDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactsController_listNotes_v1: {
        parameters: {
            query: {
                cursor?: string;
                limit: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotePageDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactsController_addNote_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.update` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactsController_removeNote_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                noteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.update` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagWithUsageDto"][];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.update` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.delete` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `contact.update` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_list_v1: {
        parameters: {
            query: {
                search?: string;
                status?: "ACTIVE" | "ARCHIVED";
                cursor?: string;
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPageDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `commerce.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `commerce.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `commerce.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `commerce.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_list_v1: {
        parameters: {
            query: {
                /** @description An order number ("10482" or "#10482"), or part of the customer's name or email. */
                search?: string;
                status?: "PENDING" | "PAID" | "FULFILLED" | "SHIPPED" | "DELIVERED" | "CANCELLED" | "REFUNDED";
                contactId?: string;
                /** @description `nextCursor` from the previous page. */
                cursor?: number;
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPageDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `commerce.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `commerce.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_summary_v1: {
        parameters: {
            query: {
                contactId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOrdersSummaryDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `commerce.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `commerce.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `commerce.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationsController_list_v1: {
        parameters: {
            query: {
                /** @description Whose conversations: everyone's, yours, nobody's, or your teams'. */
                view: "all" | "mine" | "unassigned" | "team";
                /** @description "open" means OPEN or PENDING. */
                status: "open" | "all" | "OPEN" | "PENDING" | "RESOLVED" | "CLOSED";
                handler?: "AI_HANDLING" | "HUMAN_HANDLING" | "AI_ESCALATED";
                /** @description "high" matches HIGH and URGENT. */
                priority?: "high";
                /** @description Filter by the contact's lifecycle stage (leads, customers). */
                stage?: "VISITOR" | "LEAD" | "CUSTOMER";
                channelId?: string;
                tagId?: string;
                contactId?: string;
                /** @description Only conversations with customer messages you have not read. */
                unread?: boolean;
                search?: string;
                /** @description `nextCursor` from the previous page. Opaque. */
                cursor?: string;
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPageDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `conversation.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationsController_counts_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxCountsDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `conversation.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationsController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `conversation.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConversationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `conversation.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationsController_assign_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignConversationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `conversation.assign` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationsController_setTags_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetConversationTagsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `conversation.manage` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationsController_markRead_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `conversation.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationsController_listMessages_v1: {
        parameters: {
            query: {
                /** @description Load messages older than this message id. */
                before?: string;
                limit: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePageDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `conversation.read` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationsController_send_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDto"];
                };
            };
            /** @description `ORGANIZATION_ACCESS_DENIED`, or `PERMISSION_DENIED` when the role lacks: `conversation.reply` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
